[project]
name = "typedsystem-utils"
version = "0.4.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD"}
authors = [
    {name = "Yuri Ximenes", email = "ximenesyuri@gmx.ie"},
]

dependencies = [
]

[project.optional-dependencies]
git = [
    "typed @ git+https://github.com/typedsystem/typed",
    "model @ git+https://github.com/typedsystem/model"
],
pypi = [
    "typedsystem",
    "typedsystem-model"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["utils*"]
