[project]
name = "typedsystem-utils"
version = "0.4.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD"}
authors = [
    {name = "Yuri Ximenes", email = "typed@gmx.ie"},
]

[project.optional-dependencies]
pypi = [
    "typed @ typedsystem"
]
git = [
    "typed @ git+https://github.com/typedsystem/typed"
]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["utils*"]
